from langchain.output_parsers import PydanticOutputParser
from app.schemas.post import PostSummaryResponse, PostSuggestionsResponse

summary_res_parser = PydanticOutputParser(pydantic_object=PostSummaryResponse)

suggestions_res_parser = PydanticOutputParser(pydantic_object=PostSuggestionsResponse)